"use client";

import { useMemo, useState } from "react";

type Role = "buyer" | "seller" | "admin";
type Screen = { id: string; title: string; group: string };

const buyerScreens: Screen[] = [
  { id: "onboarding", title: "Знакомство", group: "Вход" },
  { id: "login", title: "Авторизация", group: "Вход" },
  { id: "home", title: "Главная агента", group: "Поиск" },
  { id: "search", title: "Поиск товара", group: "Поиск" },
  { id: "recognized", title: "Товар распознан", group: "Выбор" },
  { id: "offers", title: "10 предложений", group: "Выбор" },
  { id: "compare", title: "Сравнение", group: "Выбор" },
  { id: "passport", title: "Паспорт покупки", group: "Выбор" },
  { id: "mission", title: "Задание агенту", group: "Сделки" },
  { id: "auction", title: "Торги продавцов", group: "Сделки" },
  { id: "club", title: "Клубная цена", group: "Сделки" },
  { id: "basket", title: "Умная корзина", group: "Сделки" },
  { id: "checkout", title: "Оформление", group: "Покупка" },
  { id: "tracking", title: "Отслеживание", group: "Покупка" },
  { id: "guardian", title: "Защита покупки", group: "Покупка" },
  { id: "profile", title: "Профиль и Plus", group: "Профиль" },
  { id: "favorites", title: "Избранное и история", group: "Сервис" },
  { id: "alerts", title: "Уведомления о цене", group: "Сервис" },
  { id: "support", title: "Помощь и возврат", group: "Сервис" },
  { id: "plus", title: "Plus и семья", group: "Сервис" },
];

const sellerScreens: Screen[] = [
  { id: "seller-onboarding", title: "Подключение магазина", group: "Старт" },
  { id: "verification", title: "Проверка магазина", group: "Старт" },
  { id: "demand", title: "Новый спрос", group: "Спрос" },
  { id: "request", title: "Запрос покупателя", group: "Спрос" },
  { id: "bid", title: "Предложение цены", group: "Сделка" },
  { id: "seller-deal", title: "Безопасная сделка", group: "Сделка" },
  { id: "inventory", title: "Товары и остатки", group: "Управление" },
  { id: "analytics", title: "Результаты и выплаты", group: "Управление" },
  { id: "seller-alerts", title: "Уведомления магазина", group: "Сервис" },
  { id: "store-profile", title: "Профиль и поддержка", group: "Сервис" },
];

const adminScreens: Screen[] = [
  { id: "overview", title: "Обзор", group: "Контроль" },
  { id: "admin-demand", title: "Спрос покупателей", group: "Контроль" },
  { id: "sellers", title: "Проверка продавцов", group: "Каталог" },
  { id: "matching", title: "Сопоставление товаров", group: "Каталог" },
  { id: "admin-deals", title: "Сделки и выплаты", group: "Операции" },
  { id: "disputes", title: "Споры и возвраты", group: "Операции" },
  { id: "users", title: "Пользователи и подписки", group: "Аудитория" },
  { id: "system", title: "Система и сотрудники", group: "Настройки" },
  { id: "risk", title: "Риски и антифрод", group: "Безопасность" },
  { id: "communications", title: "Коммуникации", group: "Аудитория" },
];

const roleScreens: Record<Role, Screen[]> = {
  buyer: buyerScreens,
  seller: sellerScreens,
  admin: adminScreens,
};

const roleLabels: Record<Role, string> = {
  buyer: "Покупатель",
  seller: "Продавец",
  admin: "Админка",
};

function Badge({ children, tone = "green" }: { children: React.ReactNode; tone?: "green" | "blue" | "orange" | "gray" }) {
  return <span className={`badge ${tone}`}>{children}</span>;
}

function Action({ children, onClick, secondary = false, danger = false }: { children: React.ReactNode; onClick?: () => void; secondary?: boolean; danger?: boolean }) {
  return <button className={`action ${secondary ? "secondary" : ""} ${danger ? "danger" : ""}`} onClick={onClick}>{children}</button>;
}

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <section className={`card ${className}`}>{children}</section>;
}

function Row({ icon, title, value, green = false }: { icon?: string; title: string; value?: string; green?: boolean }) {
  return <div className="row"><span className="row-icon">{icon ?? "•"}</span><span className="row-title">{title}</span>{value && <strong className={green ? "success" : ""}>{value}</strong>}<span className="chev">›</span></div>;
}

function Product({ kind = "tv", title = "Samsung QE65Q80D, 65″", price }: { kind?: "tv" | "pods" | "robot"; title?: string; price?: string }) {
  const icons = { tv: "📺", pods: "🎧", robot: "◉" };
  return <div className="product"><div className={`product-art ${kind}`}>{icons[kind]}</div><div><strong>{title}</strong>{price && <div className="product-price">{price}</div>}</div></div>;
}

function ProgressSteps({ active = 2 }: { active?: number }) {
  const steps = ["Сравниваю характеристики", "Проверяю 47 моделей", "Получаю предложения магазинов", "Проверяю продавцов"];
  return <div className="steps">{steps.map((step, i) => <div className={`step ${i < active ? "done" : i === active ? "active" : ""}`} key={step}><span>{i < active ? "✓" : i + 1}</span><div>{step}</div></div>)}</div>;
}

function MobileShell({ role, title, children, activeTab, onBack }: { role: Role; title?: string; children: React.ReactNode; activeTab?: string; onBack?: () => void }) {
  const tabs = role === "seller" ? [["Спрос", "◎"], ["Сделки", "♧"], ["Товары", "▢"], ["Профиль", "○"]] : [["Агент", "✦"], ["Сделки", "♧"], ["Покупки", "▢"], ["Профиль", "○"]];
  return <div className="phone"><div className="phone-top"><b>9:41</b><span>▮▮▮ ◉ ▰</span></div>{title && <header className="mobile-header"><button onClick={onBack} aria-label="Назад">‹</button><h2>{title}</h2><span>•••</span></header>}<div className="mobile-body">{children}</div><nav className="bottom-nav">{tabs.map(([label, icon]) => <div className={activeTab === label ? "selected" : ""} key={label}><span>{icon}</span><small>{label}</small></div>)}</nav><div className="home-indicator" /></div>;
}

function BuyerScreen({ id, go }: { id: string; go: (id: string) => void }) {
  if (id === "onboarding") return <MobileShell role="buyer"><div className="hero-icon">✦</div><div className="center"><h1>Покупайте выгоднее</h1><p>Личный агент найдёт товар, проверит продавца и добьётся лучшей цены.</p></div><Card><Row icon="⌕" title="Сравнит цены" value="100+ предложений" /><Row icon="♢" title="Проверит надёжность" /><Row icon="▣" title="Защитит покупку" /></Card><div className="spacer" /><Action onClick={() => go("login")}>Продолжить</Action><button className="text-button" onClick={() => go("login")}>Уже есть аккаунт</button></MobileShell>;
  if (id === "login") return <MobileShell role="buyer" title="Вход"><h1>Войти в сервис</h1><p className="muted">Введите номер телефона</p><input className="field" value="+7 999 123-45-67" readOnly /><Action onClick={() => go("home")}>Получить код</Action><Action secondary onClick={() => go("home")}>Войти через Яндекс ID</Action><div className="spacer" /><p className="legal">Продолжая, вы принимаете условия сервиса</p><p className="safe-note">♢ Ваши данные защищены</p></MobileShell>;
  if (id === "home") return <MobileShell role="buyer" activeTab="Агент"><p className="eyebrow">Добрый вечер, Сергей</p><h1>Что поручить агенту?</h1><Card className="prompt-card"><p>Опишите, что хотите купить</p><div className="prompt-icons"><span>♩</span><button onClick={() => go("search")}>▣</button><span>▥</span><span>↗</span></div></Card><Action onClick={() => go("mission")}>Поручить покупку</Action><div className="quick-grid"><button onClick={() => go("search")}>⌕<small>Найти товар</small></button><button onClick={() => go("mission")}>✦<small>Подобрать лучший</small></button><button onClick={() => go("offers")}>◇<small>Проверить цену</small></button><button onClick={() => go("basket")}>▢<small>Собрать корзину</small></button></div><h3>Активные задания</h3><Card><Product /><p className="link">Агент проверяет 47 вариантов</p><div className="progress"><i style={{ width: "68%" }} /></div><button className="card-link" onClick={() => go("mission")}>Открыть задание →</button></Card></MobileShell>;
  if (id === "search") return <MobileShell role="buyer" title="Найти товар" activeTab="Агент"><div className="segments"><b>Название</b><b className="active">Фото</b><b>Штрих-код</b><b>Ссылка</b></div><div className="camera"><div className="headphones">🎧</div><span>Поместите товар в рамку</span></div><div className="camera-actions"><span>▣<small>Галерея</small></span><button onClick={() => go("recognized")} aria-label="Сфотографировать" /><span>ϟ<small>Вспышка</small></span></div><button className="text-button" onClick={() => go("recognized")}>Найти по названию</button></MobileShell>;
  if (id === "recognized") return <MobileShell role="buyer" title="Товар распознан" activeTab="Агент"><div className="large-product">🎧</div><Badge>Совпадение 98%</Badge><h2 className="center">Apple AirPods Pro 2, USB‑C</h2><Card><Row icon="⌘" title="Артикул" value="MTJV3RU/A" /><Row icon="♢" title="Состояние" value="Новые" /><Row icon="▣" title="Гарантия" value="Официальная" /></Card><p className="center"><b>Это ваш товар?</b></p><Action onClick={() => go("offers")}>Да, найти предложения</Action><Action secondary onClick={() => go("search")}>Выбрать другую модель</Action></MobileShell>;
  if (id === "offers") return <MobileShell role="buyer" title="10 предложений" activeTab="Агент"><Product kind="pods" title="Apple AirPods Pro 2" /><div className="two-actions"><button>☷ Фильтры</button><button onClick={() => go("compare")}>▣ Сравнить</button></div><select className="select"><option>По выгоде</option></select><Offer name="Яндекс Маркет" price="20 490 ₽" badge="Выбор агента" score="97/100" onClick={() => go("passport")} /><Offer name="Ozon" price="20 790 ₽" score="96/100" /><Offer name="Wildberries" price="21 150 ₽" score="94/100" /><Offer name="ТехноДом" price="20 390 ₽" badge="Безопасная сделка" score="98/100" onClick={() => go("passport")} /></MobileShell>;
  if (id === "compare") return <MobileShell role="buyer" title="Сравнить предложения" activeTab="Агент"><div className="compare-head"><b>ТехноДом<br />★ 4,9</b><b>Маркет<br />★ 4,9</b><b>Ozon<br />★ 4,8</b></div><div className="compare-table">{[["Цена", "20 390 ₽", "20 490 ₽", "20 790 ₽"], ["Доставка", "Завтра", "Завтра", "Завтра"], ["Гарантия", "1 год", "1 год", "1 год"], ["Возврат", "14 дней", "14 дней", "7 дней"]].map((r) => <div key={r[0]}>{r.map((c, i) => <span className={i === 1 ? "winner" : ""} key={c}>{c}</span>)}</div>)}</div><Card><label className="switch-row">Только проверенные <input type="checkbox" defaultChecked /></label></Card><Action onClick={() => go("passport")}>Выбрать лучшее</Action></MobileShell>;
  if (id === "passport") return <MobileShell role="buyer" title="Паспорт покупки" activeTab="Агент"><Product kind="pods" title="Apple AirPods Pro 2" price="20 390 ₽" /><div className="score">94<small>/100</small></div><Card><Row icon="⌘" title="Модель совпадает" value="98%" green /><Row icon="◇" title="Цена честная" value="−8%" green /><Row icon="○" title="Продавец" value="Проверен" green /><Row icon="▣" title="Гарантия" value="1 год" green /><Row icon="▤" title="Доставка" value="Завтра" green /></Card><Card className="ai-verdict"><b>✦ Вердикт агента</b><h3>Можно покупать</h3></Card><Action secondary onClick={() => go("compare")}>Посмотреть альтернативы</Action><Action onClick={() => go("checkout")}>Купить за 20 390 ₽</Action></MobileShell>;
  if (id === "mission") return <MobileShell role="buyer" title="Задание агенту" activeTab="Агент"><div className="message">Нужен телевизор 65″ до 100 000 ₽ для светлой комнаты. Доставка до пятницы.</div><Card><h3>✦ Понял задачу</h3><Row icon="▣" title="Диагональ" value="65″" /><Row icon="◇" title="Бюджет" value="до 100 000 ₽" /><Row icon="☀" title="Комната" value="светлая" /><Row icon="♢" title="Надёжность" value="высокая" /></Card><Card><h3>Выполняю задание</h3><ProgressSteps /></Card><Action onClick={() => go("auction")}>Показать предложения</Action></MobileShell>;
  if (id === "auction") return <MobileShell role="buyer" title="Магазины предлагают цену" activeTab="Сделки"><Product price="Предложения ещё 08:42" /><h3>6 магазинов ответили</h3><Rank n="1" name="ТехноДом · 3,2 км" price="85 900 ₽" note="Доставка завтра · ★ 4,9" winner /><Rank n="2" name="TV Маркет" price="86 200 ₽" note="Самовывоз сегодня · ★ 4,7" /><Rank n="3" name="Яндекс Маркет" price="86 900 ₽" note="Доставка завтра · ★ 4,6" /><p className="safe-note">▣ Контакты скрыты до оплаты</p><Action onClick={() => go("checkout")}>Выбрать предложение</Action></MobileShell>;
  if (id === "club") return <MobileShell role="buyer" title="Добиться лучшей цены" activeTab="Сделки"><Product kind="robot" title="Roborock Q8 Max" price="Обычная цена 37 990 ₽" /><Card className="saving-card"><p>Клубная цена</p><h1>34 990 ₽</h1><Badge>Экономия 3 000 ₽</Badge></Card><Card><h3>83 из 100 покупателей</h3><div className="progress"><i style={{ width: "83%" }} /></div><p className="muted">Нужно ещё 17 участников</p><div className="avatars">● ● ● ● ● <b>+12</b></div></Card><Card className="center"><p>До завершения</p><h1>18:42:10</h1></Card><Action secondary>Пригласить друзей</Action><Action>Присоединиться к покупке</Action></MobileShell>;
  if (id === "basket") return <MobileShell role="buyer" title="Умная корзина" activeTab="Сделки"><CartItem icon="☕" title="Кофе Lavazza 1 кг" price="1 890 ₽" /><CartItem icon="▣" title="Капсулы Finish 100 шт." price="2 990 ₽" /><CartItem icon="◉" title="Фильтр Барьер" price="1 600 ₽" /><Card><p className="muted">Если купить всё в одном месте</p><h2>6 480 ₽</h2></Card><Card className="saving-card"><h3>Агент разделил на 2 заказа</h3><Row icon="O" title="Ozon" value="3 190 ₽" /><Row icon="M" title="Яндекс Маркет" value="2 740 ₽" /><p>Итого</p><h1>5 930 ₽</h1><Badge>Экономия 550 ₽</Badge></Card><Action onClick={() => go("checkout")}>Оформить 2 заказа</Action></MobileShell>;
  if (id === "checkout") return <MobileShell role="buyer" title="Оформление" activeTab="Покупки"><Product price="85 900 ₽" /><Card><Row icon="▤" title="Курьер магазина" value="завтра, 12:00–16:00" /><p className="muted">Москва, Ленинский проспект, 136</p></Card><Card><Row icon="▰" title="Карта •• 4821" /></Card><Card className="safe-card"><h3>♢ Безопасная сделка</h3><p>Деньги поступят продавцу после получения</p></Card><Card><div className="price-line"><span>Товар</span><b>85 900 ₽</b></div><div className="price-line"><span>Доставка</span><b>0 ₽</b></div><div className="price-line total"><span>Итого</span><b>85 900 ₽</b></div></Card><Action onClick={() => go("tracking")}>Оплатить 85 900 ₽</Action></MobileShell>;
  if (id === "tracking") return <MobileShell role="buyer" title="Заказ №1842" activeTab="Покупки"><Badge>Оплачен</Badge><Product price="85 900 ₽" /><OrderSteps /><Card><Row icon="▤" title="Курьер магазина" value="12:00–16:00" /></Card><Action secondary>Связаться с поддержкой</Action><Card className="ai-verdict">✦ Агент контролирует заказ</Card><Action onClick={() => go("guardian")}>Заказ получен</Action></MobileShell>;
  if (id === "guardian") return <MobileShell role="buyer" title="Покупка" activeTab="Покупки"><Product price="Получено 10 мая" /><Card className="center"><div className="shield">✓</div><h2>Покупка защищена</h2><Row icon="▧" title="Электронный чек" /><Row icon="♢" title="Гарантия до 10.05.2027" /><Row icon="▥" title="Серийный номер" value="0A3K81" /></Card><Card className="timer-card"><p>До конца возврата</p><h1>12 дней</h1></Card><Row icon="!" title="Сообщить о проблеме" /><Row icon="↻" title="Оформить возврат" /><Row icon="✦" title="Оставить отзыв" /><p className="safe-note">◇ Если цена снизится, агент сообщит</p></MobileShell>;
  if (id === "profile") return <MobileShell role="buyer" activeTab="Профиль"><div className="profile-head"><div className="avatar">С</div><div><h1>Сергей</h1><p>+7 999 •••‑45‑67</p></div></div><Card className="plus-card"><h1>Plus ✦</h1><p>Ваше подтверждённое преимущество</p><h2>8 450 ₽</h2><button onClick={() => go("plus")}>Управлять подпиской</button></Card><div className="profile-actions-grid"><button onClick={() => go("favorites")}>♡<b>Избранное</b><small>12 товаров</small></button><button onClick={() => go("alerts")}>♧<b>Уведомления</b><small>3 новых</small></button><button onClick={() => go("support")}>◉<b>Поддержка</b><small>Всегда рядом</small></button><button onClick={() => go("plus")}>♧<b>Семья</b><small>3 участника</small></button></div><Card><Row icon="▰" title="Адреса и способы оплаты" /><Row icon="⌕" title="Настройки поиска" /><Row icon="⚙" title="Безопасность и данные" /></Card><button className="text-button" onClick={() => go("home")}>▣ У меня есть магазин</button></MobileShell>;
  if (id === "favorites") return <MobileShell role="buyer" title="Избранное и история" activeTab="Профиль"><div className="segments"><b className="active">Избранное</b><b>История</b><b>Списки</b><b>Покупали</b></div><Card><Product kind="robot" title="Roborock Q8 Max" price="34 990 ₽" /><div className="title-row"><Badge>Цена снизилась на 3 000 ₽</Badge><b>♡</b></div><Action onClick={() => go("alerts")}>Следить за ценой</Action></Card><Card><Product kind="pods" title="Apple AirPods Pro 2" price="20 390 ₽" /><p className="muted">Искали вчера · 10 предложений</p><Action secondary onClick={() => go("offers")}>Сравнить снова</Action></Card><Card><h3>Сохранённые поиски</h3><Row icon="⌕" title="Телевизор 65″ до 100 000 ₽" value="47 моделей" /><Row icon="⌕" title="Робот-пылесос до 35 000 ₽" value="18 моделей" /></Card></MobileShell>;
  if (id === "alerts") return <MobileShell role="buyer" title="Уведомления о цене" activeTab="Профиль"><Card className="saving-card"><Badge>Цена снизилась</Badge><Product kind="robot" title="Roborock Q8 Max" price="34 990 ₽" /><p>Стало дешевле на <b>3 000 ₽</b> с момента добавления.</p><Action onClick={() => go("passport")}>Посмотреть предложение</Action></Card><Card><h3>Моя целевая цена</h3><div className="price-line"><span>Сообщить при цене</span><b>≤ 34 500 ₽</b></div><div className="progress"><i style={{ width: "86%" }} /></div><p className="muted">До цели осталось 490 ₽</p></Card><Card><h3>Как уведомлять</h3><label className="switch-row">Push-уведомления <input type="checkbox" defaultChecked /></label><label className="switch-row">Письмо на почту <input type="checkbox" defaultChecked /></label><label className="switch-row">Только существенное снижение <input type="checkbox" defaultChecked /></label></Card><Action secondary>Изменить целевую цену</Action></MobileShell>;
  if (id === "support") return <MobileShell role="buyer" title="Помощь и возврат" activeTab="Покупки"><Card><Product price="Заказ №1842" /><Badge>Получен 10 мая</Badge></Card><h3>Что случилось?</h3><div className="support-grid"><button>▣<b>Товар повреждён</b></button><button>↻<b>Хочу вернуть</b></button><button>▤<b>Проблема с доставкой</b></button><button>◉<b>Другой вопрос</b></button></div><Card className="ai-verdict"><h3>✦ Агент поддержки</h3><p>Опишите проблему или приложите фото. Я подскажу порядок действий и сохраню сроки возврата.</p><div className="two-actions"><Action secondary>▣ Добавить фото</Action><Action>Открыть чат</Action></div></Card><Card><h3>Активное обращение #D-219</h3><div className="price-line"><span>Статус</span><b className="success">На рассмотрении</b></div><p className="muted">Ответ службы поддержки — до 2 часов</p></Card></MobileShell>;
  return <MobileShell role="buyer" title="Plus и семья" activeTab="Профиль"><Card className="plus-card"><h1>Plus ✦</h1><p>Экономия за этот месяц</p><h2>8 450 ₽</h2><Badge>Подписка окупилась в 28 раз</Badge></Card><Card><h3>Включено в Plus</h3><Row icon="✦" title="Безлимитные задания агенту" /><Row icon="◇" title="История цен за 12 месяцев" /><Row icon="♧" title="Мгновенные уведомления" /><Row icon="♢" title="Расширенная защита покупок" /></Card><Card><h3>Семейный доступ</h3><Row icon="С" title="Сергей" value="Владелец" /><Row icon="А" title="Анна" value="Участник" /><Row icon="+" title="Пригласить ещё" value="до 5 человек" /></Card><Action>Перейти на семейный за 499 ₽</Action><Action secondary>Управлять подпиской</Action></MobileShell>;
}

function Offer({ name, price, badge, score, onClick }: { name: string; price: string; badge?: string; score: string; onClick?: () => void }) {
  return <button className="offer" onClick={onClick}><div><b>{name}</b>{badge && <Badge tone="blue">{badge}</Badge>}<small>★ 4,9 · Завтра, бесплатно</small></div><div><strong>{price}</strong><Badge>{score}</Badge></div></button>;
}

function Rank({ n, name, price, note, winner }: { n: string; name: string; price: string; note: string; winner?: boolean }) {
  return <Card className={winner ? "rank winner-rank" : "rank"}><b className="rank-n">{n}</b><div><b>{name}</b><h2>{price}</h2><small>{note}</small></div>{winner && <Badge>Лучшее</Badge>}</Card>;
}

function CartItem({ icon, title, price }: { icon: string; title: string; price: string }) { return <Card className="cart-item"><span>{icon}</span><b>{title}</b><strong>{price}</strong></Card>; }

function OrderSteps() { return <div className="order-steps"><div className="done">✓ <span><b>Заказ подтверждён</b><small>9 мая, 10:15</small></span></div><div className="done">✓ <span><b>Товар проверен</b><small>9 мая, 14:40</small></span></div><div className="active">● <span><b>Передан в доставку</b><small>Заказ передан курьеру</small></span></div><div>○ <span><b>Получение завтра</b><small>10 мая, 12:00–16:00</small></span></div></div>; }

function SellerScreen({ id, go }: { id: string; go: (id: string) => void }) {
  if (id === "seller-onboarding") return <MobileShell role="seller"><div className="store-hero">▣✦</div><div className="center"><h1>Получайте готовых покупателей</h1><p>Агент отправит спрос на товары, которые есть у вас в магазине.</p></div><Card><Row icon="◇" title="Без платы за показы" /><Row icon="%" title="Комиссия только со сделки" /><Row icon="♢" title="Безопасная оплата" /></Card><div className="spacer" /><Action onClick={() => go("verification")}>Подключить магазин</Action><button className="text-button" onClick={() => go("demand")}>Войти</button></MobileShell>;
  if (id === "verification") return <MobileShell role="seller" title="Проверка магазина"><p><b>Шаг 2 из 3</b></p><div className="progress"><i style={{ width: "66%" }} /></div><Card><Row icon="✓" title="Данные компании" value="ИНН 7812345678" green /><Row icon="✓" title="Банковский счёт" value="Подтверждён" green /></Card><Card className="upload"><h3>3　Документы на торговлю</h3><p>Загрузите документы</p><Action secondary>↑ Загрузить документы</Action><Action secondary>▣ Сфотографировать</Action></Card><Card><label className="switch-row">Есть офлайн-магазин <input type="checkbox" defaultChecked /></label><Row icon="⌖" title="Санкт-Петербург, Невский пр., 42" /></Card><Action onClick={() => go("demand")}>Отправить на проверку</Action></MobileShell>;
  if (id === "demand") return <MobileShell role="seller" activeTab="Спрос"><h1>Новый спрос</h1><p className="eyebrow">▣ ТехноДом⌄</p><Card className="summary-blue"><h1>12 подходящих запросов</h1><p>Покупатели готовы купить сегодня</p></Card><DemandCard kind="tv" title="Samsung QE65Q80D, 65″" benchmark="86 900 ₽" onClick={() => go("request")} /><DemandCard kind="robot" title="Roborock Q8 Max" benchmark="37 990 ₽" onClick={() => go("request")} /></MobileShell>;
  if (id === "request") return <MobileShell role="seller" title="Запрос покупателя" activeTab="Спрос"><Card className="center"><p className="link">◷ Ответить до 09:36</p></Card><Product /><Badge>Совпадение 99%</Badge><Card><Row icon="⌖" title="Москва" /><Row icon="▤" title="Доставка до пятницы" /><Row icon="▣" title="Новый товар" /><Row icon="♢" title="Гарантия от 1 года" /></Card><Card><p className="muted">Лучшая цена маркетплейсов</p><h2>86 900 ₽</h2></Card><Card className="saving-card"><p>Чтобы стать первым</p><h1>85 900 ₽</h1><b>или лучше</b></Card><p className="safe-note">6 магазинов приглашено · 3 ответили</p><Action onClick={() => go("bid")}>Сделать предложение</Action></MobileShell>;
  if (id === "bid") return <MobileShell role="seller" title="Предложение" activeTab="Спрос"><Product /><Badge>Совпадение 99%</Badge><h3>Ваша цена</h3><input className="field price-input" value="85 900 ₽" readOnly /><p className="success">На 1 000 ₽ выгоднее маркетплейсов</p><h3>Доставка</h3><Card><label className="radio"><input type="radio" defaultChecked name="delivery" /> Курьер магазина · завтра</label><label className="radio"><input type="radio" name="delivery" /> СДЭК · 1–2 дня</label><label className="radio"><input type="radio" name="delivery" /> Самовывоз · сегодня</label></Card><Card><div className="price-line"><span>Покупатель платит</span><b>85 900 ₽</b></div><div className="price-line"><span>Комиссия 2%</span><b>−1 718 ₽</b></div><div className="price-line total success"><span>Вы получите</span><b>84 182 ₽</b></div></Card><Action onClick={() => go("seller-deal")}>Отправить предложение</Action></MobileShell>;
  if (id === "seller-deal") return <MobileShell role="seller" title="Сделка №1842" activeTab="Сделки"><Badge>Покупатель оплатил</Badge><Card className="safe-card center"><div className="shield">✓</div><h1>85 900 ₽ зарезервированы</h1><p>Деньги поступят после получения товара</p></Card><OrderSteps /><Card><b>Курьер магазина · завтра, 12:00–16:00</b><Action secondary>Указать трек-номер</Action></Card><p className="safe-note">♢ Спор и возврат защищены сервисом</p><Action onClick={() => go("inventory")}>Товар передан в доставку</Action></MobileShell>;
  if (id === "inventory") return <MobileShell role="seller" activeTab="Товары"><h1>Товары</h1><input className="field" placeholder="Название или штрих-код" /><Action secondary>＋ Добавить товар</Action><div className="mini-stats"><span><b>124</b>В наличии</span><span className="orange-text"><b>8</b>Заканчиваются</span><span><b>3</b>Скрыты</span></div><Stock kind="tv" title="Samsung QE65Q80D, 65″" note="3 шт. · 85 900 ₽" badge="Активен" /><Stock kind="robot" title="Roborock Q8 Max" note="1 шт. · 36 500 ₽" badge="Заканчивается" orange /><Stock kind="pods" title="AirPods Pro 2" note="0 шт." badge="Нет в наличии" /><Action onClick={() => go("analytics")}>Посмотреть результаты</Action></MobileShell>;
  if (id === "analytics") return <MobileShell role="seller" activeTab="Профиль"><div className="title-row"><h1>Результаты</h1><Badge tone="blue">30 дней</Badge></div><div className="stat-grid"><Stat label="Продажи" value="42" /><Stat label="Выручка" value="1 842 300 ₽" /><Stat label="Комиссия" value="36 846 ₽" /><Stat label="Конверсия" value="18%" /></div><Card><h3>Выручка</h3><div className="chart"><i /><i /><i /><i /><i /><i /><i /><i /></div></Card><Card><div className="title-row"><h3>♢ Надёжность</h3><b className="success">96/100</b></div><div className="price-line"><span>Отмены</span><b>1,2%</b></div><div className="price-line"><span>В срок</span><b>97%</b></div><div className="price-line"><span>Оценка</span><b>★ 4,9</b></div></Card><Card className="saving-card"><p>К выплате</p><h1>284 182 ₽</h1><Action>Вывести деньги</Action></Card></MobileShell>;
  if (id === "seller-alerts") return <MobileShell role="seller" title="Уведомления магазина" activeTab="Спрос"><Card className="summary-blue"><h2>5 новых покупателей</h2><p>Три запроса подходят товарам на вашем складе.</p></Card><Card><Badge tone="orange">Ответить за 7 минут</Badge><Product title="Samsung QE65Q80D, 65″" price="Ориентир 85 900 ₽" /><p>Покупатель готов оплатить сегодня · Москва</p><Action onClick={() => go("request")}>Открыть запрос</Action></Card><Card><Badge>Предложение принято</Badge><Product kind="robot" title="Roborock Q8 Max" price="34 500 ₽" /><p className="success">Подготовьте товар к отправке до 18:00</p><Action secondary onClick={() => go("seller-deal")}>Перейти к сделке</Action></Card><Card><h3>Настройки уведомлений</h3><label className="switch-row">Новый подходящий спрос <input type="checkbox" defaultChecked /></label><label className="switch-row">Изменения по сделкам <input type="checkbox" defaultChecked /></label><label className="switch-row">Остатки заканчиваются <input type="checkbox" defaultChecked /></label></Card></MobileShell>;
  return <MobileShell role="seller" title="Профиль магазина" activeTab="Профиль"><div className="profile-head"><div className="avatar">Т</div><div><h1>ТехноДом</h1><p>Проверенный магазин · 96/100</p></div></div><Card><Row icon="▣" title="Юридические данные" value="Проверены" green /><Row icon="⌖" title="Адреса магазинов" value="2" /><Row icon="▰" title="Банковский счёт" value="••••1234" /><Row icon="♢" title="Гарантии и возвраты" value="Настроены" green /></Card><Card><h3>Доставка</h3><label className="switch-row">Курьер магазина <input type="checkbox" defaultChecked /></label><label className="switch-row">СДЭК <input type="checkbox" defaultChecked /></label><label className="switch-row">Самовывоз <input type="checkbox" defaultChecked /></label></Card><Card><h3>Поддержка продавца</h3><p>Вопрос по возврату, выплате или спору можно решить в одном чате.</p><Action secondary>Открыть поддержку</Action></Card><Action onClick={() => go("seller-alerts")}>Настроить уведомления</Action></MobileShell>;
}

function DemandCard({ kind, title, benchmark, onClick }: { kind: "tv" | "robot"; title: string; benchmark: string; onClick: () => void }) { return <Card><Product kind={kind} title={title} /><p className="link">Москва · нужен до пятницы</p><p>Цена маркетплейсов <b>{benchmark}</b></p><Badge>Можно выиграть сделку</Badge><div className="chips"><span>1 шт.</span><span>Новый товар</span><span>Гарантия 1 год</span></div><Action onClick={onClick}>Предложить цену</Action></Card>; }
function Stock({ kind, title, note, badge, orange }: { kind: "tv" | "robot" | "pods"; title: string; note: string; badge: string; orange?: boolean }) { return <Card className="stock"><Product kind={kind} title={title} /><p>{note}</p><Badge tone={orange ? "orange" : badge === "Активен" ? "green" : "gray"}>{badge}</Badge><span className="toggle">●</span></Card>; }
function Stat({ label, value }: { label: string; value: string }) { return <Card><small>{label}</small><h3>{value}</h3></Card>; }

const adminMenu: Record<string, string> = { overview: "Обзор", "admin-demand": "Спрос", sellers: "Продавцы", matching: "Товары", "admin-deals": "Сделки", disputes: "Споры", users: "Пользователи", system: "Система", risk: "Антифрод", communications: "Сообщения" };

function AdminShell({ id, go, children }: { id: string; go: (id: string) => void; children: React.ReactNode }) {
  return <div className="admin-app"><aside><div className="brand-mark">✦</div>{adminScreens.map((s) => <button className={id === s.id ? "active" : ""} onClick={() => go(s.id)} key={s.id}><span>{adminMenu[s.id].slice(0, 1)}</span>{adminMenu[s.id]}</button>)}</aside><main><header><div className="admin-search">⌕ Поиск по запросам, товарам, продавцам…</div><div>♧　 Сергей · Владелец⌄</div></header>{children}</main></div>;
}

function AdminScreen({ id, go }: { id: string; go: (id: string) => void }) {
  if (id === "overview") return <AdminShell id={id} go={go}><AdminTitle title="Обзор" /><div className="admin-stats"><AdminStat label="GMV" value="18,4 млн ₽" /><AdminStat label="Выручка" value="612 400 ₽" /><AdminStat label="Успешные сделки" value="1 284" /><AdminStat label="Активные покупатели" value="8 942" /></div><div className="admin-grid three"><Card><h3>Сделки и оборот</h3><LineChart /></Card><Card><h3>Воронка сделок</h3><div className="funnel"><span>Запросы <b>12 840</b></span><span>Предложения <b>6 210</b></span><span>Оплаты <b>1 284</b></span></div></Card><Card><h3>Состояние системы</h3>{["Ozon", "Яндекс Маркет", "Wildberries", "Платежи"].map(x => <div className="status-line" key={x}><i />{x}<b>Активен</b></div>)}</Card></div><div className="admin-stats small"><AdminStat label="Средняя экономия" value="8,7%" /><AdminStat label="Ответ продавца" value="4 мин" /><AdminStat label="Споры" value="1,1%" /></div></AdminShell>;
  if (id === "admin-demand") return <AdminShell id={id} go={go}><AdminTitle title="Спрос покупателей" action="Экспорт" /><Filters /><div className="split-layout"><Card><AdminTable headers={["Запрос", "Товар", "Город", "Приглашено", "Ответили", "Лучшая цена", "Статус"]} rows={[["#1842", "Samsung QE65Q80D", "Москва", "24", "9", "86 900 ₽", "Идут торги"], ["#1841", "Roborock Q8 Max", "СПб", "18", "7", "34 990 ₽", "Выбрано"], ["#1840", "AirPods Pro 2", "Казань", "15", "6", "20 490 ₽", "Идут торги"], ["#1839", "iPhone 15 128GB", "Екатеринбург", "20", "11", "63 990 ₽", "Завершён"]]} /></Card><Card className="detail-panel"><Badge tone="blue">Запрос #1842</Badge><h3>Телевизор 65″ до 100 000 ₽</h3><p>Для светлой комнаты · доставка до пятницы</p><Row icon="○" title="Анонимный покупатель" value="Рейтинг 4,8" /><h1>18:42:10</h1><p className="muted">До конца торгов</p><h4>Приглашённые продавцы</h4><Row icon="Т" title="ТехноДом" value="Ответил" green /><Row icon="М" title="ЭлектроМаркет" value="Ответил" green /><Action danger>Остановить торги</Action></Card></div></AdminShell>;
  if (id === "sellers") return <AdminShell id={id} go={go}><AdminTitle title="Проверка продавцов" /><div className="admin-stats small"><AdminStat label="На проверке" value="18" /><AdminStat label="Проверены" value="426" /><AdminStat label="Риск" value="7" /></div><div className="split-layout"><Card><AdminTable headers={["Продавец", "Статус", "Обновлён"]} rows={[["ТехноДом", "На проверке", "14 мая"], ["ЭлектроМаркет", "На проверке", "14 мая"], ["BestTech", "На проверке", "13 мая"], ["ЦифроГрад", "Нужны данные", "13 мая"], ["ТехникаПлюс", "Проверен", "12 мая"]]} /></Card><Card className="seller-detail"><div className="title-row"><h2>▣ ТехноДом</h2><Badge tone="orange">На проверке</Badge></div><div className="detail-columns"><div><p>ИНН <b>7812345678</b></p><p>Адрес <b>Санкт-Петербург, ул. Мира, 42</b></p><p>Банк <b>АО «Тинькофф Банк»</b></p><p>Счёт <b>••••1234</b></p><h4>Загруженные документы</h4><div className="docs">▧　▧　▧　+3</div></div><div><h4>Проверка данных</h4><p className="success">✓ ЕГРЮЛ</p><p className="success">✓ Банк</p><p className="success">✓ Адрес</p><p className="orange-text">! Документы</p></div></div><div className="two-actions"><Action danger>Отклонить</Action><Action>Подтвердить продавца</Action></div></Card></div></AdminShell>;
  if (id === "matching") return <AdminShell id={id} go={go}><AdminTitle title="Сопоставление товаров" /><div className="admin-stats small"><AdminStat label="Автоматически" value="94,8%" /><AdminStat label="Нужна проверка" value="37" /></div><div className="matching-grid"><Card><h3>Источники</h3><Product title="Samsung QE65Q80D 65″ · Ozon" price="86 900 ₽" /><Product title="Samsung QE65Q80D 65″ · Маркет" price="86 990 ₽" /><Product title="Samsung QE65Q80D 65″ · ТехноДом" price="87 500 ₽" /></Card><Card><h3>Канонический товар</h3><Product /><Badge>Уверенность 87%</Badge><div className="attribute-table"><p><span>Модель</span><b>QE65Q80D</b><i>✓</i></p><p><span>Диагональ</span><b>65″</b><i>✓</i></p><p><span>Цвет</span><b>Чёрный</b><i>✓</i></p><p className="warn"><span>Штрих-код</span><b>Различается</b><i>!</i></p></div><div className="three-actions"><Action>Это один товар</Action><Action secondary>Разные товары</Action><Action secondary>Исправить модель</Action></div></Card><Card><h3>✦ Объяснение ИИ</h3><p>Модели совпадают по четырём из пяти ключевых параметров. Разные штрих-коды могут относиться к партиям поставки.</p><h4>История</h4><p className="success">✓ Ozon ↔ Маркет · 96%</p><p className="success">✓ Ozon ↔ ТехноДом · 92%</p></Card></div></AdminShell>;
  if (id === "admin-deals") return <AdminShell id={id} go={go}><AdminTitle title="Сделки и выплаты" action="Экспорт" /><div className="admin-stats"><AdminStat label="Оборот" value="18,4 млн ₽" /><AdminStat label="Зарезервировано" value="2,1 млн ₽" /><AdminStat label="К выплате" value="684 200 ₽" /><AdminStat label="Комиссия" value="612 400 ₽" /></div><div className="split-layout"><Card><AdminTable headers={["Сделка", "Покупатель", "Продавец", "Сумма", "Комиссия", "Статус"]} rows={[["#1842", "Иван Петров", "ТехноДом", "85 900 ₽", "1 718 ₽", "К выплате"], ["#1841", "Анна Смирнова", "ЭлектроМаркет", "34 990 ₽", "699 ₽", "Выплачено"], ["#1840", "Дмитрий Волков", "М.Видео", "20 490 ₽", "410 ₽", "Доставляется"], ["#1839", "Елена Кузнецова", "BestTech", "63 990 ₽", "1 279 ₽", "К выплате"]]} /></Card><Card className="detail-panel"><Badge>К выплате</Badge><h3>Сделка #1842</h3><Product price="85 900 ₽" /><div className="price-line"><span>Покупатель</span><b>85 900 ₽</b></div><div className="price-line"><span>Комиссия</span><b>1 718 ₽</b></div><div className="price-line total"><span>Продавцу</span><b>84 182 ₽</b></div><p className="success">● Резерв активен</p><Action danger>Приостановить выплату</Action><Action>Подтвердить выплату</Action></Card></div></AdminShell>;
  if (id === "disputes") return <AdminShell id={id} go={go}><AdminTitle title="Споры и возвраты" /><div className="admin-stats small"><AdminStat label="Открытые" value="14" /><AdminStat label="Срочные" value="3" /><AdminStat label="Среднее решение" value="5 ч" /></div><div className="dispute-grid"><Card><h3>Очередь споров</h3>{["#D-219 · Повреждён экран", "#D-218 · Не работает звук", "#D-217 · Товар не получен", "#D-216 · Не соответствует"].map((x, i) => <div className={`case ${i === 0 ? "active" : ""}`} key={x}>{x}<Badge tone={i < 2 ? "orange" : "gray"}>{i === 0 ? "15 мин" : "3 ч"}</Badge></div>)}</Card><Card><div className="title-row"><h2>#D-219 · Повреждён экран</h2><Badge tone="orange">Срочно</Badge></div><div className="evidence"><div><h4>Покупатель</h4><p>Иван Петров</p></div><div><h4>Продавец</h4><p>ТехноДом</p></div></div><h4>Доказательства</h4><div className="photo-evidence"><span>📦<small>14 мая, 13:58</small></span><span>🖥️<small>14 мая, 13:59</small></span><span>▧<small>14 мая, 14:00</small></span></div><p className="success">✓ Доставлено 14 мая, 11:40</p></Card><Card><h3>Принять решение</h3>{["Возврат покупателю", "Выплата продавцу", "Частичная компенсация"].map((x, i) => <label className="radio" key={x}><input type="radio" defaultChecked={i === 0} name="decision" /> {x}</label>)}<textarea className="textarea" placeholder="Комментарий для сторон" /><Action>Принять решение</Action></Card></div></AdminShell>;
  if (id === "users") return <AdminShell id={id} go={go}><AdminTitle title="Пользователи и подписки" /><div className="admin-stats"><AdminStat label="Всего пользователей" value="84 290" /><AdminStat label="Plus" value="8 412" /><AdminStat label="MRR" value="2,51 млн ₽" /><AdminStat label="Отток" value="3,2%" /></div><div className="split-layout"><Card><LineChart /><AdminTable headers={["Пользователь", "Статус", "Подписка", "Экономия", "Покупки"]} rows={[["Иван Петров", "Активен", "Plus", "18 450 ₽", "12"], ["Анна Смирнова", "Активен", "Бесплатный", "6 120 ₽", "6"], ["Дмитрий Волков", "Активен", "Plus", "24 870 ₽", "15"], ["Елена Кузнецова", "Заблокирован", "Бесплатный", "1 230 ₽", "1"]]} /></Card><Card className="detail-panel"><h2>Сергей</h2><Badge>Plus активна</Badge><h1>18 450 ₽</h1><p>Сэкономлено за всё время</p><Row title="Поисковые запросы" value="142" /><Row title="Покупки" value="12" /><Row title="Жалобы" value="0" /><Action>Начислить бонус</Action><Action danger>Ограничить аккаунт</Action></Card></div><div className="plans"><Card><b>Бесплатный</b><h2>0 ₽</h2></Card><Card className="plan-active"><b>Plus</b><h2>299 ₽/мес.</h2></Card><Card><b>Семейный</b><h2>499 ₽/мес.</h2></Card></div></AdminShell>;
  if (id === "system") return <AdminShell id={id} go={go}><AdminTitle title="Система и сотрудники" action="+ Пригласить сотрудника" /><div className="integrations">{["Ozon", "Яндекс Маркет", "Wildberries", "Тинькофф Банк", "СДЭК"].map(x => <Card key={x}><b>{x}</b><p className="success">● Подключено</p><small>5 мин назад</small></Card>)}</div><div className="system-grid"><Card><h3>Сотрудники</h3><AdminTable headers={["Сотрудник", "Роль", "Статус", "2FA"]} rows={[["Сергей", "Владелец", "Активен", "Включена"], ["Мария Иванова", "Модератор", "Активен", "Включена"], ["Андрей Кузьмин", "Поддержка", "Активен", "Включена"], ["Ольга Смирнова", "Финансы", "Активен", "Включена"]]} /></Card><Card><h3>Права доступа</h3><div className="permissions"><b>Роль</b><b>Товары</b><b>Споры</b><b>Финансы</b><span>Владелец</span><i>✓</i><i>✓</i><i>✓</i><span>Модератор</span><i>✓</i><i>—</i><i>—</i><span>Поддержка</span><i>—</i><i>✓</i><i>—</i><span>Финансы</span><i>—</i><i>—</i><i>✓</i></div></Card><Card><h3>Журнал действий</h3><p>14:32 · Сергей · Изменил комиссию</p><p>14:15 · Мария · Объединила товары</p><p>13:57 · Андрей · Закрыл спор #D-217</p><p>12:48 · Ольга · Сформировала выплату</p></Card></div></AdminShell>;
  if (id === "risk") return <AdminShell id={id} go={go}><AdminTitle title="Риски и антифрод" action="Настроить правила" /><div className="admin-stats"><AdminStat label="Проверено сделок" value="1 284" /><AdminStat label="Остановлено" value="23" /><AdminStat label="Сумма риска" value="418 900 ₽" /><AdminStat label="Ложные срабатывания" value="0,8%" /></div><div className="split-layout"><Card><AdminTable headers={["Событие", "Участник", "Сумма", "Риск", "Причина", "Статус"]} rows={[["#R-904", "SmartStore", "129 900 ₽", "Высокий", "Новый счёт", "Заморожено"], ["#R-903", "Иван Петров", "85 900 ₽", "Средний", "3 карты", "Проверка"], ["#R-902", "ЦифроГрад", "63 990 ₽", "Высокий", "Отмены 18%", "Ограничен"], ["#R-901", "Анна К.", "34 990 ₽", "Низкий", "Новый адрес", "Разрешено"]]} /></Card><Card className="detail-panel"><Badge tone="orange">Высокий риск</Badge><h2>SmartStore</h2><p>Изменён банковский счёт за 12 минут до выплаты.</p><Row title="Сделки за 24 часа" value="14" /><Row title="Сумма к выплате" value="129 900 ₽" /><Row title="Совпадение устройства" value="Нет" /><Row title="Проверка ЕГРЮЛ" value="Пройдена" green /><Action danger>Заблокировать выплату</Action><Action secondary>Запросить документы</Action></Card></div></AdminShell>;
  return <AdminShell id={id} go={go}><AdminTitle title="Коммуникации" action="+ Создать сообщение" /><div className="admin-stats"><AdminStat label="Push доставлено" value="94,2%" /><AdminStat label="Открытия" value="38,7%" /><AdminStat label="Переходы" value="12,4%" /><AdminStat label="Отписки" value="0,3%" /></div><div className="communications-grid"><Card><h3>Автоматические уведомления</h3><AdminTable headers={["Событие", "Канал", "Аудитория", "Статус"]} rows={[["Цена снизилась", "Push + email", "Покупатели", "Активно"], ["Новый спрос", "Push", "Продавцы", "Активно"], ["Сделка оплачена", "Push + SMS", "Продавцы", "Активно"], ["Срок возврата", "Push", "Покупатели", "Активно"]]} /></Card><Card><h3>Предпросмотр сообщения</h3><Card className="ai-verdict"><Badge>Цена снизилась</Badge><h2>Roborock Q8 Max — 34 990 ₽</h2><p>Товар из избранного подешевел на 3 000 ₽. Предложение проверено агентом.</p><Action>Посмотреть цену</Action></Card><h4>Правила отправки</h4><p>Не чаще 2 уведомлений в день · тихие часы 22:00–09:00 · персональная частота.</p></Card><Card><h3>Последние рассылки</h3><p><b>Клубная цена на технику</b><br /><span className="muted">42 800 получателей · 41% открытий</span></p><p><b>Вернитесь к сохранённой корзине</b><br /><span className="muted">8 410 получателей · 35% открытий</span></p><p><b>Новые заказы для магазинов</b><br /><span className="muted">426 продавцов · 68% открытий</span></p></Card></div></AdminShell>;
}

function AdminTitle({ title, action }: { title: string; action?: string }) { return <div className="admin-title"><div><p className="eyebrow">Управление сервисом</p><h1>{title}</h1></div>{action && <button>{action}</button>}</div>; }
function AdminStat({ label, value }: { label: string; value: string }) { return <Card><small>{label}</small><h2>{value}</h2><span className="success">+8,7% за 7 дней ↗</span></Card>; }
function LineChart() { return <div className="line-chart"><div className="grid-lines" /><svg viewBox="0 0 500 180" preserveAspectRatio="none"><polyline points="0,145 55,125 105,135 160,80 220,102 275,55 335,88 390,35 445,62 500,28" fill="none" stroke="#315cff" strokeWidth="5" /><polyline points="0,158 55,148 105,152 160,112 220,125 275,95 335,110 390,82 445,96 500,72" fill="none" stroke="#16a15f" strokeWidth="4" /></svg></div>; }
function Filters() { return <div className="filters"><button>Статус: Все⌄</button><button>Город: Все⌄</button><button>07.05.2026 — 14.05.2026</button><button>Ещё фильтры⌄</button></div>; }
function AdminTable({ headers, rows }: { headers: string[]; rows: string[][] }) {
  const columns = { gridTemplateColumns: `repeat(${headers.length}, minmax(70px, 1fr))` };
  return <div className="admin-table"><div className="thead" style={columns}>{headers.map(h => <b key={h}>{h}</b>)}</div>{rows.map((row, ri) => <div className="trow" style={columns} key={ri}>{row.map((v, i) => <span key={i} className={i === row.length - 1 ? "status-cell" : ""}>{v}</span>)}</div>)}</div>;
}

export function PrototypeExperience() {
  const [role, setRole] = useState<Role>("buyer");
  const [screenId, setScreenId] = useState("home");
  const screens = roleScreens[role];
  const index = screens.findIndex((s) => s.id === screenId);
  const currentIndex = index < 0 ? 0 : index;
  const current = screens[currentIndex];
  const groups = useMemo(() => Array.from(new Set(screens.map((s) => s.group))), [screens]);

  const changeRole = (next: Role) => {
    setRole(next);
    setScreenId(next === "buyer" ? "home" : roleScreens[next][0].id);
  };
  const go = (id: string) => setScreenId(id);
  const previous = () => setScreenId(screens[Math.max(0, currentIndex - 1)].id);
  const next = () => setScreenId(screens[Math.min(screens.length - 1, currentIndex + 1)].id);

  return <main className="prototype-page"><header className="prototype-header"><div className="prototype-brand"><span>✦</span><div><b>Агент покупок</b><small>40 экранов прототипа + рабочий backend</small></div></div><div className="role-switch">{(["buyer", "seller", "admin"] as Role[]).map((r) => <button className={r === role ? "active" : ""} key={r} onClick={() => changeRole(r)}>{roleLabels[r]}</button>)}</div><div className="prototype-header-links"><a href="/live-search">Живой поиск</a><a href="/backend">Интеграции</a></div></header><div className={`prototype-workspace ${role === "admin" ? "admin-mode" : ""}`}><aside className="screen-list"><p className="eyebrow">Страницы проекта</p>{groups.map((group) => <div key={group}><h4>{group}</h4>{screens.filter((s) => s.group === group).map((s) => <button key={s.id} onClick={() => go(s.id)} className={s.id === current.id ? "active" : ""}><span>{screens.indexOf(s) + 1}</span>{s.title}</button>)}</div>)}</aside><section className="stage"><div className="stage-toolbar"><button onClick={previous} disabled={currentIndex === 0}>← Назад</button><div><b>{current.title}</b><span>{currentIndex + 1} из {screens.length}</span></div><button onClick={next} disabled={currentIndex === screens.length - 1}>Дальше →</button></div>{role === "buyer" && <BuyerScreen id={current.id} go={go} />}{role === "seller" && <SellerScreen id={current.id} go={go} />}{role === "admin" && <AdminScreen id={current.id} go={go} />}</section><aside className="flow-panel"><p className="eyebrow">Карта сценария</p><h3>{role === "buyer" ? "Путь покупателя" : role === "seller" ? "Путь продавца" : "Контур управления"}</h3><p>{role === "buyer" ? "Поиск, честная цена, безопасная покупка, уведомления и помощь после получения." : role === "seller" ? "От входящего спроса до выплаты, поддержки магазина и повторных продаж." : "Контроль данных, денег, продавцов, рисков, коммуникаций и сотрудников."}</p><div className="flow-steps">{screens.map((s, i) => <button onClick={() => go(s.id)} className={s.id === current.id ? "active" : i < currentIndex ? "done" : ""} key={s.id}><span>{i < currentIndex ? "✓" : i + 1}</span><div><small>{s.group}</small><b>{s.title}</b></div></button>)}</div><div className="prototype-note"><b>Проверено на полноту</b><p>Во всех ролях есть основной сценарий, уведомления, поддержка, безопасность, история действий и понятный следующий шаг.</p></div></aside></div></main>;
}

type CustomerTab = "search" | "favorites" | "orders" | "help" | "profile";

const customerTabs: Array<{ id: CustomerTab; label: string; icon: string }> = [
  { id: "search", label: "Поиск", icon: "⌕" },
  { id: "favorites", label: "Цены", icon: "♡" },
  { id: "orders", label: "Покупки", icon: "▣" },
  { id: "help", label: "Помощь", icon: "?" },
  { id: "profile", label: "Профиль", icon: "○" },
];

export default function Home() {
  const [tab, setTab] = useState<CustomerTab>("search");

  return <main className="customer-app">
    <header className="customer-header">
      <button className="customer-brand" onClick={() => setTab("search")}><span>✦</span><b>Агент покупок</b></button>
      <nav aria-label="Основная навигация">{customerTabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav>
      <button className="customer-avatar" onClick={() => setTab("profile")} aria-label="Открыть профиль">С</button>
    </header>

    {tab === "search" && <>
      <section className="customer-hero">
        <div className="customer-hero-copy"><span className="customer-kicker">Личный агент выгодной покупки</span><h1>Найдём дешевле.<br />Проверим всё важное.</h1><p>Один поиск по маркетплейсам и небольшим магазинам — с итоговой ценой, доставкой, надёжностью продавца и защитой покупки.</p></div>
        <form className="customer-search" action="/live-search" method="get"><label htmlFor="customer-query">Что хотите купить?</label><div><input id="customer-query" name="q" defaultValue="Apple AirPods Pro 2 USB-C" placeholder="Название, модель или штрих-код" /><button type="submit">Найти лучшее</button></div><p><a href="/live-search?mode=photo">▣ По фото</a><a href="/live-search?mode=barcode">▥ По штрих-коду</a><span>До 10 проверенных вариантов</span></p></form>
        <div className="customer-proof"><span><b>Итоговая цена</b><small>товар + доставка</small></span><span><b>Проверка продавца</b><small>рейтинг и гарантии</small></span><span><b>Контроль после покупки</b><small>цена, возврат, поддержка</small></span></div>
      </section>
      <section className="customer-content">
        <div className="customer-section-title"><div><span className="customer-kicker">Почему это удобно</span><h2>Агент делает сложное за вас</h2></div><a href="/live-search">Проверить реальный поиск →</a></div>
        <div className="benefit-grid"><article><span>01</span><h3>Узнаёт точную модель</h3><p>По названию, фотографии, ссылке или штрих-коду. Перед поиском вы подтверждаете результат.</p></article><article><span>02</span><h3>Считает настоящую выгоду</h3><p>Сравнивает итог к оплате, сроки, гарантию и надёжность, а не только цену в карточке.</p></article><article><span>03</span><h3>Подключает малые магазины</h3><p>Проверенные продавцы могут предложить цену лучше маркетплейсов через безопасную сделку.</p></article></div>
        <section className="trust-strip"><div><span>◇</span><h3>Понятно, почему предложение лучшее</h3><p>Для каждой рекомендации показываем свежесть цены, совпадение модели, условия возврата и причину оценки.</p></div><a href="/live-search">Найти товар</a></section>
      </section>
    </>}

    {tab === "favorites" && <section className="customer-dashboard"><div className="customer-section-title"><div><span className="customer-kicker">Избранное и цены</span><h1>Агент следит за выгодой</h1><p>Сообщим только о настоящем снижении итоговой цены.</p></div><button onClick={() => setTab("search")}>+ Добавить товар</button></div><div className="watch-grid"><article><div className="watch-art">📺</div><div><span className="watch-status">Цена снизилась</span><h3>Samsung QE65Q80D, 65″</h3><p>Лучшая цена сейчас</p><b>85 900 ₽</b><small>−7 100 ₽ за 14 дней</small></div><a href="/live-search?q=Samsung%20QE65Q80D">Сравнить</a></article><article><div className="watch-art">◉</div><div><span className="watch-status neutral">Наблюдаем</span><h3>Roborock Q8 Max</h3><p>Ждём цену ниже 35 000 ₽</p><b>36 490 ₽</b><small>Обновлено сегодня</small></div><a href="/live-search?q=Roborock%20Q8%20Max">Проверить</a></article></div></section>}

    {tab === "orders" && <section className="customer-dashboard"><div className="customer-section-title"><div><span className="customer-kicker">Мои покупки</span><h1>Всё под контролем</h1><p>Чек, гарантия, возврат и помощь хранятся в одном месте.</p></div></div><article className="protected-order"><div><span className="watch-status">Защищена</span><h2>Samsung QE65Q80D, 65″</h2><p>Заказ №1842 · доставка завтра, 12:00–16:00</p></div><div className="order-progress"><i /><i /><i className="pending" /><span>Оплачен</span><span>Передан курьеру</span><span>Получение</span></div><div className="order-actions"><button>Связаться с поддержкой</button><button>Условия возврата</button></div></article></section>}

    {tab === "help" && <section className="customer-dashboard"><div className="customer-section-title"><div><span className="customer-kicker">Помощь</span><h1>Не оставим после оплаты</h1><p>Агент помогает с доставкой, возвратом, гарантией и спором.</p></div></div><div className="help-grid"><button><span>▤</span><b>Где мой заказ?</b><small>Проверить доставку</small></button><button><span>↻</span><b>Оформить возврат</b><small>Пошаговая помощь</small></button><button><span>!</span><b>Проблема с товаром</b><small>Открыть обращение</small></button><button><span>◉</span><b>Написать агенту</b><small>Ответим в чате</small></button></div><section className="help-promise"><b>Среднее время ответа — 3 минуты</b><span>История обращения и все подтверждения сохраняются.</span></section></section>}

    {tab === "profile" && <section className="customer-dashboard"><div className="profile-banner"><span className="customer-avatar large">С</span><div><h1>Сергей</h1><p>Покупатель · профиль защищён</p></div></div><div className="profile-dashboard-grid"><article className="plus-dashboard"><span>Plus ✦</span><h2>Больше выгоды, без скрытых условий</h2><ul><li>неограниченные уведомления о цене</li><li>приоритетные задания агенту</li><li>семейный доступ и помощь с возвратами</li></ul><div><b>399 ₽/месяц</b><button>Попробовать бесплатно</button></div></article><article className="profile-links"><button>Адреса и оплата <span>›</span></button><button>Настройки поиска <span>›</span></button><button>Безопасность и данные <span>›</span></button><button>Семейный доступ <span>›</span></button></article></div></section>}

    <footer className="customer-footer"><span>Агент покупок · честный выбор без скрытой наценки</span><div><a href="/prototype">Все 40 экранов</a><a href="/backend">Админка интеграций</a></div></footer>
  </main>;
}
